project_id = "zuzbwklzmcrszdjyepqe"

[functions.generate-artwork]
verify_jwt = false

[functions.calculate-natal-chart]
verify_jwt = false

[functions.ai-interpret]
verify_jwt = false

[functions.proxy-image]
verify_jwt = false

[functions.analyze-artwork]
verify_jwt = false